[project]
name = "qwen3-reranker-8b"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.11.0",
    "torch>=2.9.1",
    "transformers>=4.57.1",
]
